### ISSUE TITLE
Problem with USB on a similar Acer notebook. Any ideas?

### ISSUE THREAD

**Issue by jpaderaldo** [longluuly/Ryzentosh-Acer-aspire-7-A715-42G-R6ZR-Opencore-EFI#2]
I have a Acer Aspire 5 A515-45-R6KH which is kind of similar to your Aspire 7. I've built EFIs for it multiple times but I always get the same problem: When booting macOS or recovery, the boot process gets up to apple logo but only continues if I tap my USB keyboard and move my USB mouse a bit. If they aren't connected I cant proceed with the boot. Do you have any idea what could be happening? Did something like that also happed to you?

**Comment by longnguyen245** [comment]
Some AMD Ryzen machines have problems with usb, you can add the kext below to fix the problem https://github.com/RattletraPM/GUX-RyzenXHCIFix

**Comment by jpaderaldo** [comment]
THANK YOU SO MUCH!!! This solved the problem! I've been looking for this solution for 1 whole week. Good Bless you @longluuly
