### ISSUE TITLE
I have lenovo ideapad 3

### ISSUE THREAD

**Issue by kis12345678** [longluuly/Ryzentosh-Acer-aspire-7-A715-42G-R6ZR-Opencore-EFI#3]
Can i use this efi on my laptop i have also same processor amd ryzen 5 5500u ( Lucienne )

**Comment by longnguyen245** [comment]
> Can i use this efi on my laptop i have also same processor amd ryzen 5 5500u ( Lucienne )

you need to create a new efi for your machine

**Comment by kis12345678** [comment]
Can you suggest how can you make this efi

**Comment by longnguyen245** [comment]
> Can you suggest how can you make this efi

Follow this guide: https://chefkissinc.github.io/
