### ISSUE TITLE
After installation not starting for first boot

### ISSUE THREAD

**Issue by rakshitbharat** [longluuly/Ryzentosh-Acer-aspire-7-A715-42G-R6ZR-Opencore-EFI#6]
I installed but it doesn't start for first set-up or boot 
![17190593574796766017217396874562](https://github.com/long5436/Ryzentosh-Acer-aspire-7-A715-42G-Opencore-EFI/assets/17176729/6440b28e-ffdf-44fc-8848-1135c6ccf358)

**Comment by longnguyen245** [comment]
Have you disabled the NootedRed kext yet?

**Comment by rakshitbharat** [comment]
after installation yet i havent started it for first time also, let me try with my other computer to disabled the NootedRed kext

**Comment by rakshitbharat** [comment]
so i have a working copy for first boot,
very important note even for first boot have to remove NootedRed kext

**Comment by rakshitbharat** [comment]
@long5436 Thanks for instant reply

**Comment by longnguyen245** [comment]
Congratulations, you have fixed the problem
